excludes = [".gitignore", "*.lock"]

[formatter.clang-format]
command = "clang-format"
options = ["-i"]
includes = "*.h"

[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.toml]
command = "taplo"
options = ["format"]
includes = ["*.toml"]
