[package]
name = "ghc-rts-sys"
version.workspace = true
edition.workspace = true
build = "build.rs"

[build-dependencies]
bindgen.workspace = true
build-utils.workspace = true

[dependencies]
libc.workspace = true
