[package]
name = "include"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
build = "build.rs"

[build-dependencies]
cbindgen = { version = "0.28.0", default-features = false }
